### PR TITLE
fixed some clippy warnings + markdown

### PR DESCRIPTION
**Pull request by llogiq**

### CODE REVIEW

**Comment by mhintz** [comment]
Wow, this is awesome! I didn't even know about clippy before, I'm definitely going to start using it going forward.

I agree with all of the changes, except for one little thing: I disagree with Rust's convention about avoiding explicit return statements everywhere. I love it for short functions, but I find that in longer functions an explicit return improves readability, because that word jumps out at me while I'm skimming a long chunk of code far better than the last statement in the function does. In this library, I've used an explicit return statement in places where I think it ties the function together nicely and makes it more readable.

Is it possible to merge this without the explicit return changes?

**Comment by llogiq** [comment]
I suppose I could revert those (once I find the time). 

However, please bear in mind that the majority of the Rust community by and large has decided that explicit returns should only be used to break control flow. By not following this tradition, you actually make your code harder to follow for other Rustaceans. Also by not familiarizing yourself with it, you will find it harder to read other people's code. So please reconsider your position on explicit returns and follow the one true Rust way... :wink:

**Comment by mhintz** [comment]
I reconsidered your really helpful changes to the library and merged them. Thanks a lot for the PR!

**Comment by llogiq** [comment]
You're welcome.

**Pull request merged**
